server:
  port: 9069
spring:
  application:
    name: order-item-query
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: A1234567890@a
    url: jdbc:mysql://localhost:3306/fmmall?characterEncoding=utf-8
eureka:
  client:
    service-url:
      defaultZone: http://zhangsan:123456@localhost:8761/eureka
mybatis:
  mapper-locations: classpath:mappers/*
  type-aliases-package: com.qfedu.fmmall.entity