server:
  port: 8001
spring:
  application:
    name: api-user-login
  redis:
    host: 192.168.0.226
    port: 6379
    database: 0
eureka:
  client:
    service-url:
      defaultZone: http://zhangsan:123456@localhost:8761/eureka
feign:
  circuitbreaker:
    enabled: true

