spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fmmall?characterEncoding=utf-8
      username: root
      password: A1234567890@a
      initial-size: 1
      min-idle: 1
      max-active: 20
      connect-timeout: 3000
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  redis:
    host: 192.168.0.226
    port: 6379
    database: 0
  elasticsearch:
    uris: http://192.168.0.226:9200


mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.qfedu.fmmall.entity

redisson:
  addr:
    singleAddr:
      host: redis://192.168.0.226:6379
      database: 0