server:
  port: 8014
spring:
  application:
    name: api-order-submit
  rabbitmq:
    host: 192.168.0.226
    port: 5672
    virtual-host: host1
    username: root
    password: A1234567890@a
eureka:
  client:
    service-url:
      defaultZone: http://zhangsan:123456@localhost:8761/eureka
feign:
  circuitbreaker:
    enabled: true
